on:
  pull_request:
  push:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dprint/check@v2.3
    - run: dprint config update
    - run: ./format-json.py items.json
    - run: git diff --exit-code --patch
